name: 'Tala Testing '
favicon: null
layout_spectrum: 0.35495
typography_spectrum: 0.63425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4375
  lightness: 0.15786515944637358
  saturation: 0.375
  rhythmicContrast: 0.25409420556388795
purpose: []
