name: 'Tala Testing '
favicon: null
layout_spectrum: 0.11189
typography_spectrum: 0.63425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff7ff'
    - '#a97d6c'
    - '#5b3e31'
    - '#120000'
    - '#ffafcd'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
