name: 'Tala Testing '
favicon: null
layout_spectrum: 0.11189
typography_spectrum: 0.63425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfb'
    - '#2a1e2b'
    - '#9b796d'
    - '#00bba4'
    - '#c40040'
  brandStrength: 0
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
